[package]
name = "bevy-test"
version = "0.1.0"
authors = ["Rob Parrett <robparrett@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "c434f57de1da4e1d05ca0daa6e1080460e0caa9c" }
bevy = { path = "../bevy-fork/" }
